name: halasat_cinema_mobile
description: Vodu client for streaming movies and tv shows.

version: 1.0.0+1

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  built_value: ^6.3.0
  built_collection: ^4.1.0

  url_launcher: ^5.0.1
  http: ^0.12.0
  android_intent: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.1.3
  built_value_generator: ^6.3.0

flutter:
  uses-material-design: true
