name: halasat_cinema_mobile
description: Vodu client for streaming movies and tv shows.

version: 1.1.2+4

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  built_value: ^6.3.0
  built_collection: ^4.1.0
  http: ^0.12.0
  android_intent: ^0.3.0+1
  incrementally_loading_listview: ^0.0.4+3
  carousel_slider: ^1.1.0
  flutter_appavailability: ^0.0.21
  simple_permissions: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.1.3
  built_value_generator: ^6.3.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/post-placeholder.png
    - assets/featured-placeholder.jpg
